server:
  port: 8087
spring:
  redis:
    host: 10.20.152.63
    password: 123
dubbo:
  application:
    name: shop_order
  consumer:
    check: false
    timeout: 1000
  registry:
    address: zookeeper://10.20.152.63:2181
