server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    mode: HTML5
  servlet:
    multipart:
      max-file-size: 5MB
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://10.20.152.63:2181
  consumer:
    check: false
    timeout: 1000
fdfs:
  so-timeout: 1000
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list:
   - 10.20.152.63:22122
image:
  path: http://10.20.152.63/

